# Generated by Django 4.2.7 on 2024-02-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('pacientes_atendidos', models.IntegerField(default=0)),
                ('especialista', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('desocupada', 'Desocupada'), ('ocupada', 'Ocupada')], default='desocupada', max_length=10)),
                ('tipo_consulta', models.CharField(choices=[('Pediatría', 'Pediatría'), ('Urgencia', 'Urgencia'), ('CGI', 'Consulta General Integral')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('historia_clinica', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('grupo_edad', models.CharField(choices=[('niño', 'Niño'), ('joven', 'Joven'), ('anciano', 'Anciano')], max_length=10)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('estatura', models.FloatField(blank=True, null=True)),
                ('fumador', models.BooleanField(default=False)),
                ('anos_fumador', models.IntegerField(default=0)),
                ('dieta_asignada', models.BooleanField(default=False)),
            ],
        ),
    ]
