# Generated by Django 4.2.7 on 2024-02-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paciente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='prioridad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
